// ✏️  זה הקובץ היחיד שצריך לערוך.
// 1. שימו את התמונות בתיקייה "photos".
// 2. הוסיפו שורה לכל תמונה או סרטון (mp4): שם הקובץ + כיתוב מצחיק.
// 3. התמונות מוצגות בסדר הזה, מלמעלה למטה.

const PHOTOS = [
  { src: "photos/leash.jpg", caption: "הוא אמר 'כן' ומאז הוא רק אומר 'הב' 🐕" },
  { src: "photos/casino.jpg", caption: "כשאומרים לו 'תביא חברים לחתונה' והוא לוקח את זה ברצינות 🃏" },
  { src: "photos/disco.jpg", caption: "שבת בערב: קדחת. ראשון בבוקר: גב תפוס 🕺" },
  { src: "photos/jungle.jpg", caption: "ככה הוא רואה את עצמו במראה כל בוקר 💪🌴" },
  { src: "photos/superman.jpg", caption: "כוח העל האמיתי שלו? לתלות כביסה בלי שיבקשו ממנו 🦸" },
  { src: "photos/album.jpg", caption: "האלבום החדש 'ילד טוב ילד רע'. בקרוב בכל תחנות הדלק 🎤" },
  { src: "photos/podcast.jpg", caption: "הפודקאסט שלו: 3 מאזינים, שניים מהם אמא שלו 🎙️" },
  { src: "photos/karaoke-sleep.jpg", caption: "הקהל היה מרותק. חלק יותר מאחרים 😴🎤" },
  { src: "photos/karaoke-live.mp4", caption: "הופעה חיה מחדר הקריוקי. הקישו לסאונד, על אחריותכם 🎤🔊" },
  { src: "photos/karaoke-selfie.jpg", caption: "קריוקי, 2 בלילה. ברקע: הלהקה במיטבה 🤳" },
  { src: "photos/sidewalk-help.jpg", caption: "יד לעזרה? לא צריך, הוא מרגיש מצוין על המדרכה 😁" },
  { src: "photos/sidewalk-thumbsup.jpg", caption: "'אני בסדר גמור', הוא הודיע מהרצפה 👍" },
  { src: "photos/monkey.jpg", caption: "תמונה קבוצתית. רק אחד פה מתנהג בבגרות 🐒" },
  { src: "photos/tiger.jpg", caption: "ישן כמו תינוק. השותף לחדר קצת נוחר 🐯" },
  { src: "photos/bobblehead.jpg", caption: "מהדורת אספנים: ראש גדול, רגליים קטנות. נאמן למקור ⚽" },
  { src: "photos/hangover.jpg", caption: "ההנגאובר 4: הפעם הם לא זוכרים אפילו איך קוראים להם 🕶️" },
  { src: "photos/thailand-comic.jpg", caption: "תאילנד 2026: הסיפור המלא. הקישו והגדילו עם שתי אצבעות 🐒📸" },
  { src: "photos/beegees.jpg", caption: "הבי ג'יז החדשים. עוד אין שיר, אבל השיער כבר מוכן 🕺" },
  { src: "photos/toy-story.jpg", caption: "סדרת הצעצועים החדשה. סוללות לא כלולות, אדוויל כן 🧸💊" },
  { src: "photos/crew-01.jpg", caption: "הלוק: דייג שהלך לאיבוד בקניון 🎣" },
  { src: "photos/crew-02.jpg", caption: "מחכה לאוכל כבר 40 דקות. והוא לא מוותר 🍽️" },
  { src: "photos/crew-03.jpg", caption: "גזרה חדשה במדים. עוד לא אישרו אותה 🪖" },
  { src: "photos/crew-04.jpg", caption: "נעצר על ידי האימפריה. שוב 🚨" },
  { src: "photos/crew-05.jpg", caption: "סלפי זוגי. אחד מהם לא ידע שהוא בתמונה 🤳" },
  { src: "photos/crew-06.jpg", caption: "בוקר טוב, מאפיה 🎩" },
  { src: "photos/crew-07.jpg", caption: "המדים מגוהצים, הביטחון בשמיים 😎" },
  { src: "photos/crew-08.jpg", caption: "ככה הוא ענה ל'מתי אתה מתחתן?' עד עכשיו 🖕" },
  { src: "photos/crew-09.jpg", caption: "משמרת לילה. הוא שומר. בעיניים עצומות 😴" },
  { src: "photos/crew-10.jpg", caption: "זכה במשהו. עדיין לא ברור במה 🎟️" },
  { src: "photos/crew-11.jpg", caption: "משקפי שמש בלילה. כי ככה עושים 🕶️" },
  { src: "photos/crew-12.jpg", caption: "החולצה אמרה 'השם ישלח לך כלה'. עבד 🙏👰" },
  { src: "photos/crew-13.jpg", caption: "הסלפי הכי מסתורי שלו. עדיין מחכים שיוריד את הכובע 🧢" },
  { src: "photos/crew-14.jpg", caption: "מלאך עם כוס קוקטייל. אמין לגמרי 😇🍹" },
  { src: "photos/crew-15.jpg", caption: "חדר בריחה ראשון. היחיד שהם יצאו ממנו בזמן 🔐" },
  { src: "photos/crew-16.jpg", caption: "דוגמנים בחצות. הסוכנות עדיין לא התקשרה 📸" },
  { src: "photos/crew-17.jpg", caption: "טיפוח לפני החתונה. התחיל לפני שלוש שנים 🧖" },
  { src: "photos/crew-18.jpg", caption: "אוזני ארנב מבלונים. אל תשאלו 🎈🐰" },
  { src: "photos/crew-19.jpg", caption: "שנייה לפני שגנבו לו את הכובע 🧢" },
  { src: "photos/crew-20.jpg", caption: "מחובר לכל המערכות. חוץ מלמוח ⚡" },
  { src: "photos/crew-21.jpg", caption: "מה? ככה עובדים פה 🤷" },
  { src: "photos/crew-22.jpg", caption: "מסדר את הכובע כבר שעה. זה חשוב לו 🧢" },
  { src: "photos/crew-23.jpg", caption: "הפפיון הוורוד הוא חלק מהמדים. כנראה 🎀" },
  { src: "photos/crew-24.jpg", caption: "בתור לקיוסק. לא לדבר איתו עכשיו 🥪" },
  { src: "photos/crew-25.jpg", caption: "נסיעה ארוכה באוטובוס. מאוד ארוכה 💋🚌" },
  { src: "photos/crew-26.jpg", caption: "משקפיים של ספורטאי, חיוך של מי שלא עשה ספורט מעולם 🕶️" },
  { src: "photos/crew-27.jpg", caption: "משקפי מגן. ליתר ביטחון 🥽" },
  { src: "photos/crew-28.jpg", caption: "הפסקה של 5 דקות. כבר שעה 🚬" },
  { src: "photos/crew-29.jpg", caption: "הספה הזאת ראתה דברים 🛋️" },
  { src: "photos/crew-30.jpg", caption: "תמונת פספורט, ניסיון שלישי 👅" },
  { src: "photos/crew-31.jpg", caption: "שני אנשים, שריר אחד. תנחשו של מי 💪" },
  { src: "photos/crew-32.jpg", caption: "שלום עם נשק. הכי ישראלי שיש ✌️" },
  { src: "photos/crew-33.jpg", caption: "כשהמצלמה הקדמית נדלקת בהפתעה 🤨" },
  { src: "photos/crew-34.jpg", caption: "הבוס והעובד. לא ברור מי זה מי 👔" },
  { src: "photos/crew-35.jpg", caption: "גנן מקצועי, יום ראשון בעבודה 🌿" },
  { src: "photos/crew-36.jpg", caption: "מלחמה בעשבים שוטים. העשבים מנצחים 🌱" },
  { src: "photos/crew-37.jpg", caption: "סלפי עם החבר הכי טוב. של השבוע 🤝" },
  { src: "photos/crew-38.jpg", caption: "הסוויטה המלכותית 🛏️👑" },
  { src: "photos/crew-39.jpg", caption: "הקוסמים של ארץ עוץ 🧙" },
  { src: "photos/crew-40.jpg", caption: "אותם קוסמים, אחרי שנגמר הקסם 🎭" },
  { src: "photos/crew-41.jpg", caption: "מנזר שאולין. המדיטציה החזיקה 4 דקות 🧘" },
  { src: "photos/crew-42.jpg", caption: "נתפסו. שוב. הפעם עם תלבושות מתאימות 🚔" },
  { src: "photos/crew-43.jpg", caption: "שהכוח יהיה איתך. בעיקר ביום החתונה ⚔️" },
  { src: "photos/crew-44.jpg", caption: "מועצת הג'די מתכנסת לדון בכלה 🌌" },
  { src: "photos/crew-45.jpg", caption: "סוכנים חשאיים. כל כך חשאיים שאפילו הם לא יודעים מה המשימה 🕵️" },
  { src: "photos/crew-46.jpg", caption: "ארבעה גמדים על מדף 🎩" },
  { src: "photos/crew-47.jpg", caption: "הוויקינגים בדרך לחתונה. המלצרים בכוננות 🪓" },
  { src: "photos/crew-48.mp4", caption: "ריקוד במשמרת. הוא ברקע, כמו תמיד 💃" },
  { src: "photos/rushmore.jpg", caption: "הר ראשמור של החבר'ה. חצובים באבן, כמו הבדיחות שלהם 🗿" },
];
